### PR TITLE
Feature: /info bot command

### PR DESCRIPTION
**Pull request by nicklvh**
# Description of your changes

Create the /info bot command, when used results in an embed showing some basic details about the current bot.

Also changes the /info user command, making it so whenever a user isn't provided, the interaction author is used instead.

# What changes will the user experience?

Nothing unless they use the new commands

# Resolved / Related Issues

- [x]  Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
- Closes #issue...

# Validation Requirements

How did you test these changes?
- [x] Do your latest changes result in a successful build?
- [x] Did you thoroughly test the changes for your intended behavior? 

**What are the steps we need to take to reproduce intended behavior? What should we try to deviate from to see for any potential unintended behavior?**

Use the commands

### Optional
- [x] Opt in for automatic merges

**Screenshots/Videos**

image

### CODE REVIEW

**Review by Tellinq — APPROVED** [review]
LGTM

**Comment by Tellinq** [comment]
Only thing I would disagree with is that I would argue the user would notice the info bot command, which is something I would put in the changelog. Not a big deal right now since we are just getting a baseline. Once we have releases this will be something I will persist about before approving.

**Comment by june1011** [comment]
@nicklvh should set `inline=False` and then its good to merge

**Review by Tellinq — APPROVED** [review]
All good to me. Feel free to merge when ready.

**Comment by nicklvh** [comment]
image

For future reference, here is the updated command

**Pull request merged**
